### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by iamh2o** [telatin/seqfu2#10]
Thank you for such a strong contribution to the universe of Bfx tools.  I am adopting seqfu today :-). Your final point in you paper really resonated with me (the lack of standardized, performant, reliable tools for most simple tasks <--- where the worst errors do tend to be rooted in).  Thank you 👍

**Comment by telatin** [comment]
Thank you for the feedback, it's really appreciated. 
Some minor improvements are coming with a new release today, in case you want to `conda update` it :)
