### ISSUE TITLE
SeqFu stats/qual mixed command?

### ISSUE THREAD

**Issue by SciLiciumTheo** [telatin/seqfu2#11]
Hi,

Would it be possible to implement a single function that computes
1. number of read
2. read length distribution descriptors (Avg / Min / Max / Quantiles) 
3. read quality descriptors (Avg / Min / Max / Quantiles)

Currently, 1. and 2. can be accessed with seqfu `stats` and 3. with `qual`, but this necessitates to read the file twice.

Thanks in advance

**Comment by telatin** [comment]
Thanks for the feedback, I will experiment something in the future on this topic

**Comment by telatin** [comment]
We close it for now, as it will take a while before we have the time to address this. Thanks again for  your feedback
