### ISSUE TITLE
Read subsampling

### ISSUE THREAD

**Issue by simone-pignotti** [telatin/seqfu2#16]
Please describe the feature that you want adding an example input and output
Hi, thanks for this great tool! I suggest adding a simple read subsampling option to `cat` (or a separate command), which is always useful :)
Thanks!

**Comment by telatin** [comment]
Hi @simone-pignotti ,
thanks for the feedback.

If you need "random" sampling, I would recommend tools like `seqkit`.

SeqFu cat already implements some features to allow, effectively, a subsampling (assuming reads are randomly distributed, like it is for raw datasets):
```
Options:
  -k, --skip STEP        Print one sequence every STEP [default: 0]
  --skip-first INT       Skip the first INT records [default: -1]
  --jump-to STR          Start from the record after the one named STR
                         (overrides --skip-first!)
```

Suppose I want 25% of the reads, I can print one read every 4 (`seqfu cat --skip 4 ...`). If this kind of subsampling is helpful for you, I can easily expand with arbitrary fractions like `--subsample 0.21` in the next release. But it wont be random, as I want to keep it deterministic and single-pass.

Cheers

**Comment by simone-pignotti** [comment]
Hi @telatin, thanks a lot for the quick reply! Indeed, I meant a random sampling.
Thanks for the suggestion anyways, `--skip` works in most cases, and I totally understand your wish to keep it deterministic.
