### ISSUE TITLE
check does not identify mismatched sequence and quality length

### ISSUE THREAD

**Issue by nolanmaier** [telatin/seqfu2#17]
**Describe the bug**
`check` returns OK for a FASTQ containing an entry with a mismatched sequence and quality length. The third entry in the attached FASTQ file has a much shorter sequence length than the quality length. I expected an ERR in the output table. However, the output looks like this:

> OK      SE      bad.fastq       2       143     0

The program only reports 2 entries in the file. However there are 5 entries in the file. It appears that any entry after the broken entry is not reported by the program.

**To Reproduce**
`seqfu check bad.fastq`
 
**Environment:**
-Linux
-BioGrids installation
-Seqfu version 1.17.0
 
**Additional context**
[bad.fastq.zip](https://github.com/telatin/seqfu2/files/11728846/bad.fastq.zip)

**Comment by telatin** [comment]
Thanks a million for reporting. I will check it out and get back to you
-- 
–––––––––––––––––––––––––––––––
*A n d r e a   T e l a t i n*

**Comment by telatin** [comment]
Ok, thanks for providing a test file, I tried it and got
```
OK      SE      /Users/telatina/Downloads/bad.fastq     2       143     0
```
If you notice, it detects 2 sequences, *i. e.* there are two valid sequences before the file becomes garbage. Your error is typical (sequence/quality length mismatch) so it makes sense to report it / detect it differently from other problems.

For paired end, I guess it can happen in rare occasions to have errors "in frame", and will make a test case for that as well.

Just as a note: if you
```
seqfu cat bad.fastq > bad_parsed.fastq
```
you get a valid file with the two valid sequences, this is basically why the error is not detected with the current implementation. Will work on it

**Comment by telatin** [comment]
Ok, I made a different FQ parser for this case. It won't support Sanger FASTQ (multiline), but in the NGS era this was never used and I think it's a reasonable sacrifice.

I'm testing it as a separate `--deep` flag, but maybe I could make it the default, what is your suggestion here?

**Comment by nolanmaier** [comment]
Thanks for addressing this so quickly!

I agree that the loss of multiline FASTQ support is not a huge problem. Is there an easy way to check if a file is multiline and gracefully return a warning message if so?

I would support making the new parser the default as the current default does not actually perform all of the checks specified in the [documentation](https://telatin.github.io/seqfu2/tools/check.html).

**Comment by telatin** [comment]
I temporarily updated the docs and added --deep, will test a bit more before making a release, it's too slow at the moment. If you want to test you can compile, or if you tell me if you are using Linux  or Mac I can drop some test binaries here
Cheers
