### ISSUE TITLE
manifest file : absolute-path vs absolute-filepath

### ISSUE THREAD

**Issue by RachBioHaz** [telatin/seqfu2#18]
Hi,
I just wanted to know if there was a specific flag I should be using to have the manifest file column labelled with absolute-filepath instead of absolute-path. 

The command I'm using is:
```
seqfu metadata ~/Project/NL3/01Raw/  > ~/Project/NL3/01Raw/manifest.tsv
```

The manifest file is created:
first column  header = `sample-id` 
second column header  = `absolute-path` (should be absolute-filepath)

Thanks for your help.

**Comment by telatin** [comment]
Thanks for reporting, will look into this and either fix or add a flag for it!

**Comment by telatin** [comment]
Found the issue
Can you confirm you have single end reads in that directory please?

**Comment by RachBioHaz** [comment]
Hi, sorry for the delay - have been away. Yes, the reads are single end reads.
Cheers
