### ISSUE TITLE
Adding space to name

### ISSUE THREAD

**Issue by kabilov** [telatin/seqfu2#21]
**Describe the bug**
Using **interleave** or **deinterleave** adds a space after the read name

**To Reproduce**
seqfu deinterleave -o 123 sample01.fq
 
**Environment:**
 - OS: Ubuntu 18.04
 - Installation BioConda
 - Version 1.20.0
 
**Additional context**
"@F350022422L1C001R00200006849/1"  --> "@F350022422L1C001R00200006849/1 "

Of course this is not critical, but for example my script threw an error.

**Comment by telatin** [comment]
Wow that’s bad!
Thanks for reporting will look into it asap

**Comment by telatin** [comment]
Fixed in 1.20.3
