### ISSUE TITLE
seqfu qual induces segmentation fault

### ISSUE THREAD

**Issue by ImagoXV** [telatin/seqfu2#28]
**Describe the bug**
seqfu qual triggers a segmentation fault when ran. 
It did so on Nanopore gzipped and flat fastq file as positional argument and as stdin too | -

**To Reproduce**
```
 user@machine:$ seqfu qual barcode01/BC01.fastq.gz 
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)

 user@machine:$ zcat barcode01/BC01.fastq.gz | seqfu qual -
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)

 user@machine:$ seqfu qual BC01.fastq 
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)

```
**Environment:**
 - Ubuntu 22.04.5
 - Installation BioConda
 - Version 1.22.3
 
**Additional context**
I also noted ```qual``` is absent from the --help output. Maybe it's related to this bug. 

Ciao Andrea !

**Comment by ImagoXV** [comment]
Hi Andrea, 

I tested and it works fine ! 
I'm not 100% sure what I was expecting. Just global statistics about quality. Like mean median, qscore. Pretty much the FastQC like, but way lighter and interminal mostly. But please, do not put energy into that. I'm not requesting a feature. I was just reporting a bug !

Thanks again !

**Comment by telatin** [comment]
Note that the "fix" will avoid failing, but the --maxlen INT will still allocate the vector size so for long reads to have the mean quality by position you should adjust that accordingly.
I'm planning a more extensive quality check in any case, if you have ideas feel free to drop them here :) ciao!
