### ISSUE TITLE
test suite fails with latest version

### ISSUE THREAD

**Issue by michaelgelliot** [telatin/seqfu2#8]
Hi there, I was wondering if there is any reason the test suite is designed to fail if attempting to build the latest version. For example version 1.9.0 fails on the last test with a "prerelease warning". However the git api has "prerelease": false for version 1.9.0. This is making it tricky to add the latest version to our linux repository (bioarchlinux) without patching the test script to remove the final test, which I would prefer not to do...
Thanks for any advice, best wishes,
Mick

**Comment by telatin** [comment]
Hi @michaelgelliot, I changed the test suite that now will pass when the version tested is == to the remote version (it is, actually, a pre-release check and not a part of the test suite, as you correctly spotted). Thanks for reporting and let me know if this fixes your issue
